114 email confirmation
AppMaintainers/beloved-projects pull request #117
Opened 2024-02-16 13:57 UTC by zsuzsibelteky

closes  #114

2024-02-19 13:01 UTC, Gregurevic requested changes
Ezzel a fejlesztéssel átalakítottuk a bejelentkezés menetét. Szuper lenne legalább 1-2 tesztet látni arról, hogy az új bejelentkezési folyamat hogyan működik.

2024-02-19 13:21 UTC, kiskoza commented on db/migrate/20240214140701_add_confirmable_to_user.rb
> +    change_table :users, bulk: true do |t|
teljesen rendben van így, performance okai vannak, hogy miért szereti a rubocop összevonni

2024-02-19 13:22 UTC, kiskoza commented on db/migrate/20240214140701_add_confirmable_to_user.rb
> +    User.update(confirmed_at: DateTime.now)
a két módosítás szorosan összefügg, szerintem rendben van, ha itt marad, akkor lenne haszna külön mozgatni, ha lennének külön adat migrációink

2024-02-19 15:42 UTC, zsuzsibelteky commented on config/initializers/devise.rb
> +  config.allow_unconfirmed_access_for = 15.days
Nem kaptam új kommenteket, úgyhogy írtam hozzá egyet.

2024-02-19 15:43 UTC, zsuzsibelteky commented on spec/models/user_spec.rb
> -    context "when an email is already in use" do
mert a devise-ban benne van az, hogy nem enged 2x ugyanazzal az emaillel regisztrrálni

2024-02-20 10:07 UTC, Gregurevic requested changes

2024-02-20 10:07 UTC, Gregurevic commented on config/initializers/devise.rb
> +  # config.secret_key = 'a91be4cafcc9b97ba9116272c4c2e676654638705982c9351035ff52b38114f5f43821e6d9862dc53a808f7edf790e4618dd739de04e1888c3f6941b22947667'
Lehet, hogy amikor futtattad a devise generátorát, akkor megváltoztatta ezt a sort, és véletlenül benne maradt a change-ek között.

2024-02-20 10:07 UTC, Gregurevic commented on config/initializers/devise.rb
> +  # config.pepper = '36d951c191fd40ce518c8a44b72efb3fd8598026e44b4355fd70d1d86cb7520683357fb88bce0032f3e19abccd8583a74843d000eb67812d6183280c518e23e2'
Ez is mintha a devise generátor után került volna bele.

2024-02-20 10:07 UTC, Gregurevic commented on db/migrate/20240214140701_add_confirmable_to_user.rb
> +    User.update(confirmed_at: DateTime.now)
Bocsi, itt kicsit egymásra futott 1-2 komment.

Le tudod ellenőrizni, hogy  a fenti kóddal működik-e a `rails db:rollback` && `rails db:migrate`?

Ha nem, akkor vissza kellene hozzuk az up - down függvényeket.

2024-02-20 11:48 UTC, zsuzsibelteky commented on db/migrate/20240214140701_add_confirmable_to_user.rb
> +    User.update(confirmed_at: DateTime.now)
működik

2024-02-20 12:49 UTC, Gregurevic approved these changes

2024-02-21 09:51 UTC, kiskoza requested changes

2024-02-21 09:51 UTC, kiskoza commented on db/migrate/20240214140701_add_confirmable_to_user.rb
> +    User.update(confirmed_at: DateTime.now)
hiányzik innen a User class újra-definiálása, mi történik a migrációval, ha a későbbiekben átnevezzük vagy töröljük a User classt? a migrációs class tetjére kérlek rakj oda egy üres User class definíciót

2024-02-21 10:04 UTC, kiskoza approved these changes

2024-02-21 10:04 UTC, merged