115 magic link to log in
AppMaintainers/beloved-projects pull request #119
Opened 2024-03-28 12:26 UTC by zsuzsibelteky

closes #115

2024-04-04 14:29 UTC, Gregurevic requested changes

2024-04-04 14:29 UTC, Gregurevic commented on app/controllers/magic_links_controller.rb
> +    skip_authorization
Egy rövid kommenttel jelezzük, hogy miért skip-peljük!

2024-04-04 14:29 UTC, Gregurevic commented on app/controllers/magic_links_controller.rb
> +    skip_authorization
Egy rövid kommenttel jelezzük, hogy miért skip-peljük!

2024-04-04 14:29 UTC, Gregurevic commented on app/views/magic_link_mailer/login_instructions.html.erb
> +<p>Hello,</p>
Az email szövegezéséhez volt bármilyen formai követelmény? Az issue alatt nem találtam ilyet.

2024-04-04 14:29 UTC, Gregurevic commented on db/migrate/20240327133336_add_trackable_to_devise.rb
> +    User.update(last_sign_in_at: DateTime.now)
Erre miért van szükség? `nil` értékekkel nem működik a magic link generátor?

2024-04-04 14:29 UTC, Gregurevic commented on spec/factories/users.rb
> +    last_sign_in_at { 1.day.ago.change(usec: 0) }
```ruby
# e helyett:
1.day.ago.change(usec: 0)
# nem elég annyi, hogy:
1.day.ago
```

2024-04-04 14:29 UTC, Gregurevic commented on spec/factories/users.rb
> +    last_sign_in_at { 1.day.ago.change(usec: 0) }
Ez elméletileg egy nullable field. Én nem raknám bele a factory-ba, ha csak nem ad valamilyen plusz hasonlóságot az éles adatokhoz hogy benne van. Lefutnak a tesztek e nélkül is?

2024-04-04 14:29 UTC, Gregurevic commented on spec/factories/users.rb
> +    last_sign_in_at { 1.day.ago.change(usec: 0) }
Ha benne szeretnéd hagyni a factory-ban, akkor érdemes lenne a többi fake-elt adatot átnézni, hogy koherens-e velük. A fenti kód:
```ruby
    confirmed_at { DateTime.now }
    last_sign_in_at { 1.day.ago.change(usec: 0) }
```
Valószínűleg nem fordul elő valós futás + adatok mellett.

2024-04-04 14:29 UTC, Gregurevic commented on spec/requests/magic_link_spec.rb
> +    context 'with successful login since the token was created' do
Itt nekem nehezen érthető a teszt neve.

2024-04-04 14:29 UTC, Gregurevic commented on spec/requests/magic_link_spec.rb
> +      let(:token_generated_at) { 30.minutes.ago }
Ha jól értem a tesztet, akkor lehet, hogy ez
```ruby
30.minutes.ago
# helyett
30.minutes.from_now
```
kéne legyen?

2024-04-04 14:44 UTC, zsuzsibelteky commented on spec/requests/magic_link_spec.rb
> +      let(:token_generated_at) { 30.minutes.ago }
Nem, mert itt nekem az kell, hogy a token legyen lejárva (15 percig érvényes egy, de tuti ami biztos alapon várunk 30at 30), a from_now-val előre megyünk az időben, de az nekem nem jó, mert a tokennek már lejártnak kell lennie.

2024-04-12 09:02 UTC, zsuzsibelteky commented on db/migrate/20240327133336_add_trackable_to_devise.rb
> +    User.update(last_sign_in_at: DateTime.now)
ebbe belefutottam és nem működik

2024-04-12 09:05 UTC, zsuzsibelteky commented on spec/factories/users.rb
> +    last_sign_in_at { 1.day.ago.change(usec: 0) }
más pontossággal használja az időpontot és a sima .ago nem jó

2024-04-12 10:37 UTC, Gregurevic commented on spec/requests/magic_link_spec.rb
> +    context 'with successful login since the token was created' do
Esetleg egy ilyen?
> with successful login the remaining tokens are invalid

2024-04-12 12:35 UTC, Gregurevic commented on spec/factories/users.rb
> +    last_sign_in_at { 1.day.ago.change(usec: 0) }
Csináljunk belőle trait-et.

2024-04-15 09:24 UTC, Gregurevic approved these changes
Köszi! Így szuper!

2024-04-15 10:24 UTC, merged