127 deactivate projects
AppMaintainers/beloved-projects pull request #159
Opened 2024-05-16 13:58 UTC by zsuzsibelteky

closes #127

2024-05-17 08:53 UTC, Gregurevic requested changes
Nekem még hiányzik egy-két dolog ebből a PR-ból.
- egy teszt, ami a `projects#destroy` működését ellenőrzi
- két teszt, ami (admin, sima user) policy_scope-jában teszteli a deactivated_at működését
- Nincs lekezelve az az eset, amikor deaktivált Project linkjét/account-ját stb. módosítja a felhasználó.
  - ez elvileg csak policy változásokkal fog járni
  - illetve a kapcsolódó tesztek változásával

Utóbbihoz hint:
```ruby
class LinkPolicy < ApplicationPolicy
  #...
  def destroy?
    previous_validatiotion_statement && ProjectPolicy.new(user, record.project).update?
  end
  #...
end
```

2024-05-17 08:53 UTC, Gregurevic commented on app/controllers/projects_controller.rb
> +    if policy(@project).valid_deactivated_at?(DateTime.now)
Itt olyan érzésem van, mintha a `valid_deactivated_at?` -re szeretnéd bízni, hogy a felhasználó tudja-e deaktiválni a projektet.

Eddig ugye a sima policy-kat arra használtuk, hogy "az adott erőforráshoz hozzáférhet-e a felhasználó?", és az attribute_policy-kat arra, hogy "az egyes attribútumokat módosíthatja-e valamilyen értékre a felhasználó?".
- Ez alapján érdemes lenne az authorizációt továbbra is a sima policy-ra bízni (pl az egyel fentebbi kommentem). 
- Szerintem attribute_policy-ra itt nincs szükségünk.
  - Felhasználófüggetlenül mindig ugyanazt az értéket fogjuk beállítani (`DateTime.now`).
  - Ugyanazok a felhasználók állíthatják be azt az értéket, mint akik a többi attribútumát is tudják módosítani a Project-nek.

2024-05-17 08:53 UTC, Gregurevic commented on app/controllers/projects_controller.rb
> +        flash[:alert] = 'This project cannot be deactivated.'
Itt szerintem érdemes lenne a `show` oldalra redirect-telni. Így megmutatnánk a felhasználónak, hogy a Project változatlan.

2024-05-17 08:53 UTC, Gregurevic commented on app/policies/project_policy.rb
> +  def valid_deactivated_at?(next_value)
Szerintem ez a függvény véletlenül maradt bent.

2024-05-17 08:53 UTC, Gregurevic commented on app/policies/project_policy.rb
> +    admin? || record.maintainers.include?(user)
Én az `index?` és a `new?` kivételével minden akciót megváltoztatnék arra, hogy csak akkor engedjük a felhasználónak, ha a `deactivated_at: nil`.

Ez azért lenne hasznos, mert a fenti formában meg tudna történni a következő:
1. User#1 bookmark-ol egy Project-et.
2. User#2 deaktiválja a Project-et
3. User#1 bookmark-kal megnyitja a Project-et
4. Megjelenik neki változatlanul a deaktivált Project, amit még update-elni is tud.

2024-05-17 08:53 UTC, Gregurevic commented on app/policies/project_policy.rb
> +        scope.where(projects: { deactivated_at: nil })
Ez csak egy suggestion, de mivel itt egyetlen táblán dolgozunk, ezért e helyett
```ruby
where(projects: { deactivated_at: nil })
```
tudjuk ezt is írni
```ruby
where(deactivated_at: nil)
```

2024-05-17 08:53 UTC, Gregurevic commented on app/policies/project_policy.rb
> +          .joins(:projects_users).where(projects_users: { user_id: user.id })
Itt egy kicsit áttekinthetőbb lenne a kód, ha a `where` klózok egymást követnék. e.g.:
```ruby
scope
  .joins(:stuff)
  .where(asd: 'asd')
  .where(sdf: 'sdf')
```

2024-05-17 08:53 UTC, Gregurevic commented on spec/policies/admin/project_policy_spec.rb
> +    it { is_expected.to forbid_actions [] }
Ez szerintem véletlenül maradt benne. A másik tesztben szépen megszűnt, amikor már nem volt funkciója.

2024-05-21 08:55 UTC, zsuzsibelteky commented on app/controllers/projects_controller.rb
> +        flash[:alert] = 'This project cannot be deactivated.'
szerintem az összezavarná a felhasználót, eddig el akartuk vele hitetni, hogy törli a projektet, nem csak deaktiválja

2024-05-31 09:25 UTC, Gregurevic commented on app/controllers/projects_controller.rb
> +        flash[:alert] = 'This project cannot be deactivated.'
Itt mintha megbeszéltük volna szóban, hogy a komment az unhappy path-ra vonatkozott:
- happy path, deaktivált project, irányítsuk vissza a root_path-re a felhasználót
- unhappy path, nem deaktiválódott a project, mutassuk meg a felhasználónak a show oldalon, hogy még mindig elérhető a project

2024-05-31 09:50 UTC, Gregurevic requested changes
Még találtam pár apróságot.

Egy kommentet még nem zártam le az első review-ból.

Illetve nekem úgy tűnik, hogy a policy teszteknél, amikor nem scope-ot, hanem az egyes akciókat teszteljük, akkor nem tesztelünk `deactivated_at` -re.
Ezek a típusó tesztek:
```ruby
it { is_expected.to permit_actions [:create, :show, :edit, :update, :destroy] }
```
A `Project`, `Link`, `Account` erőforrásoknál mintha nem kezelnék a `deactivated_at` -es szcenáriókat.

2024-06-07 08:55 UTC, merged