58 all messages look the same
AppMaintainers/beloved-projects pull request #63
Opened 2023-07-03 12:04 UTC by zsuzsibelteky

Tost message not showing

2023-07-06 12:22 UTC, Gregurevic requested changes
Találtam egy fura styling-ot, meg egy felesleges kommentet. Ezen kívül szép munka!
Érdemes lehet a flash message-eket kiszervezni partial-be.

2023-07-06 12:22 UTC, Gregurevic commented on app/views/devise/sessions/new.html.erb
>          <%= form_for(resource, as: resource_name, url: session_path(resource_name)) do |f| %>
Itt miért tűnt el egy indent? Látszólag jó helyen volt elsőre.
```
<%= form_for %>
  <div>
    content
  </div>
<% end %>
```

2023-07-06 12:22 UTC, Gregurevic commented on app/views/layouts/application.html.erb
> +    <% # Messages %>
Szerintem nem érdemes kommentet hagynunk a kódban. Kérlek ezt vegyük ki!

E helyett csinálhatnánk egy partial-t, ami egyértelművé teszi, hogy mit is csinál az itt lévő html kód.
Ehhez arra lenne szükség, hogy a kódot mozgassuk át egy `_flash_messages.html.erb` vagy hasonló nevű fájlba.
Majd itt csak rendereljük azt ki:
```
<%= render 'flash_messages' %>
```

2023-07-06 13:15 UTC, Gregurevic approved these changes
Így szuper! :) Köszi!

2023-07-07 07:41 UTC, kiskoza requested changes

2023-07-07 07:41 UTC, kiskoza commented on app/helpers/application_helper.rb
> +  def bootstrap_class_for_toast(type)
lefedünk minden flash message típust, amit használunk? #59 -ben az új üzenetekhez `info` és `danger` lett használva, ami itt még nem szerepel

kérlek csinálj egy rebase-t a legfrissebb masterre, majd egységesítsd a flash message típusokat. mivel a `notice`-t a devise használja, érdemes lenne megtartani, de az is jó lenne, ha összesen két verziónk maradna: egy a pozitív, egy a negatív üzeneteknek. ne feledd, kétféleképpen hívhatunk flash-t, egyrészt a `flash[...]`, másrészt a `flash.now[...]` is definiálhat új típust ha nem figyelünk oda

2023-07-11 13:57 UTC, kiskoza requested changes
Szuperül sikerült az egységesítés a saját kódbázison belül, azonban a devise gem használ még két típust (`alert` és `notice`). Jó lenne ezeket is lekezelnünk, vagy teljesen áttérni rájuk

2023-07-11 13:57 UTC, kiskoza commented on app/helpers/application_helper.rb
> +    when 'error'
hibás jelszó esetén a devise `alert` típust használ. lehet ezt kellene nekünk is, hogy mindenhol jól nézen ki?

2023-07-11 13:57 UTC, kiskoza commented on app/helpers/application_helper.rb
> +    when 'success'
sikeres belépéskor a devise `notice` típust használ. lehet ezt kellene nekünk is, hogy midenhol jól nézzen ki?

2023-07-14 13:09 UTC, kiskoza approved these changes

2023-07-14 13:09 UTC, merged