create migration to remove status
AppMaintainers/beloved-projects pull request #67
Opened 2023-07-14 12:23 UTC by zsuzsibelteky

closes #62 

A status tábla és a hozzá tartozó kód részletek el lettek távolítva a kódból.

2023-07-17 11:37 UTC, Gregurevic approved these changes
Looks cool! :)

2023-07-17 12:16 UTC, kiskoza commented
Jól néz ki az eddigi kód, azonban találtam pár apróbb hiányosságot:
1. Amikor megpróbálom újra felhúzni az adatbázist (`rake db:reset`), akkor hibaüzenetet kapok
2. A ticket szövege az volt, hogy csak a `title` maradjon a projekten, viszont továbbra is meg lehet adni pár másik adatot is, amikre nincs szükségünk

2023-07-28 07:37 UTC, Gregurevic requested changes
Dolgozzuk át a seed file-t. Ez után pedig ellenőrizzük le, hogy egy friss db-vel fel tudunk-e állni.

```
rails db:reset
```

2023-07-28 07:37 UTC, Gregurevic commented on db/seeds.rb
>  # Generate microposts for a subset of users.
Eredetileg csak ehhez a kódrészlethez szerettem volna kommentet írni, de az egész seed file nagyon csúnya. Légyszi legyen ennek a PR-nak a része, hogy rendbeszedjük ezt a file-t, úgyis kb a feléhez hozzányúltunk már.

- A fájlban megtalálhatók az ősi ellenségeim a kommentek. Itt nem rossz, hogy vannak kommentjeink, viszont egy praktikusabb megoldás, ha meg is osztjuk a fejlesztővel ezeket a fájl futása közben.

```
# generate data for statuses
```

komment helyett mindenhol legyen egy konzolra írás

```ruby
puts 'creating statuses'
```

- A kommentek nem tükrözik a valóságot. "Generate microposts for a subset of users." Tudtommal nincsenek micropost-jaink. Ezeket aktualizáljuk légyszi!

- (Írnék kommentet az egyszer használatos változókra, de a következő komment ezt feloldja.)

- Nem érdemes újra feltalálni a kereket. Jelenleg rendelkezünk factory-kkal, amik tisztában vannak vele, hogy hogyan kell mintaadatokat létrehozni. Illetve rendelkezünk segédfüggvénnyel, aminek a segítségével fix számú mintarekordot tudunk létrehozni.

```ruby
5.times do |n|
  first_name  = Faker::Name.first_name
  last_name  = Faker::Name.last_name
  email = "example-#{n+1}@beloved.org"
  password = "password"
  User.create!(first_name:  first_name,
               last_name: last_name,
               email: email,
               password:              password,
               password_confirmation: password)
end
```

egy ilyen helyett valami hasonlót szeretnék látni:

```ruby
FactoryBot.create_list :user, 3
```

- Illetve egy tök hasznos dolog, ha van egy fix felhasználónk a seed file-ban, aki mindig létrejön. Így el lehet menteni localhost-ra bejelentkezéshez.

```ruby
puts 'creating VIP' # VIP helyett, ha van pl admin és kliens jogosultságunk, akkor érdemes egy-egy ilyen user-t létrehozni "creating admin" & "creating client" etc. You get the idea.
FactoryBot.create :user, email: 'that@specific.email', password: 'somethingSENSIBL3' # megadhatod, hogy mindig ugyanaz legyen a neve is. alapvetően a credentials fontos, hogy mindig ugyanaz legyen
```

2023-07-28 07:37 UTC, Gregurevic commented on db/seeds.rb
>  # Generate microposts for a subset of users.
Utánanéztem, mert szerettem volna neked rosszaló kommentet írni arra, hogy a `project` factory-ja nem változott a PR-ban. Sadly, nem rendelkezünk project factory-val. :upside_down_face: 

Az lenne a feladat, hogy hozzuk létre ezt a Factory-t.
- Ihletet tudsz meríteni a `spec/factories/users.rb` -ből.
- Mi a `spec/factories/projects.rb` -t szeretnénk létrehozni.
- Légyszi a fájl első sorában legyen `# frozen_string_literal: true`
- Bármilyen `Faker` helper-t használhatsz a `project.title` generálásához:
  - `Faker::Lorem.word`
  - `Faker::Movie.title`
  - `Faker::Hacker.say_something_smart`
  - A `Faker` doksit megtalálod többek között itt is: https://www.rubydoc.info/github/faker-ruby/faker/Faker (a baloldali menüben tudsz majd navigálni)

2023-07-31 09:40 UTC, Gregurevic approved these changes
Sokkal szebb lett a seed! :) Köszönöm!

2023-07-31 14:06 UTC, merged