Apply dashboard designs
AppMaintainers/beloved-projects pull request #69
Opened 2023-07-25 08:51 UTC by zsuzsibelteky

closes #68 
A header és a project áttekintő nézeten már az új design szerepel.
Az eddigi tesztek ebben a formában nem lesznek jók, mert a kijelentkezés és a profil is átkerültem más helyre. A design más oldalakon kicsit összecsúszik még, ezeket majd akkor javítjuk, ha megvan azoknak az oldalaknak is a design-ja.

2023-07-25 09:19 UTC, Gregurevic requested changes
Két kisebb kommentem volt. Alapvetően szép munka.

A CI viszont piros. Zöld CI nélkül nem tudom átengedni a PR-t. :(

2023-07-25 09:19 UTC, Gregurevic commented on .tool-versions
> +nodejs 18.16.1
Egy ilyen változást érdemes lenne külön PR-ba szervezni. :sweat_smile: Nem baj, hogy nem tartozik hozzá issue.

Amennyiben a monstani master-en feljebb tudunk lépni bármilyen további teendő nélkül nodejs verzióval, akkor kérlek készíts két PR-t! Ezek legyenek a következők:
- egy PR, ahol csak a nodejs verzió változik
- a jelenlegi PR, csak a nodejs bump nélkül

Ellenkező esetben nem kell két külön PR. Légyszi válaszolj majd erre a kommentre!

Nagyon szuper, hogy külön commit-ban van a bump! :) ++

2023-07-25 09:19 UTC, Gregurevic commented on app/views/home/index.html.erb
> +        <!-- Page pre-title -->
Légyszi a kommenteket vegyük ki! Kettőt is látok ezen az oldalon.

2023-07-28 08:44 UTC, kiskoza commented on .tool-versions
> +nodejs 18.16.1
legközelebb így csináljuk majd, most nem érdemes ezzel lassítani a fejlesztést, nincs más package, ami nodejs-t használna

2023-07-28 09:24 UTC, Gregurevic approved these changes
Thank you! :)

2023-07-28 09:46 UTC, merged