70 rubocop cleanup
AppMaintainers/beloved-projects pull request #71
Opened 2023-07-26 13:17 UTC by viktorJMarton

2023-07-26 13:38 UTC, Gregurevic requested changes
Szép munka!

Eddig 15 commit-ot láttam, azok rendben vannak. Tök szuper, hogy javításonként külön commit-ba kerülnek a módosítások!

Viszont légyszi a PR-nak legyen leírása!
- Ha van kapcsolódó issue, akkor legyen belinkelve.
- Ha ezen felül kell bármi plusz infót tudni a PR-ról, akkor írd bele azt is légyszi!

2023-07-27 06:59 UTC, Gregurevic approved these changes
Köszi a readme update-et! :)

2023-07-28 07:49 UTC, Gregurevic approved these changes
Okés! Rendben van! :)

Az `STDOUT` => `$stdout` egy érdekes olvasás volt. ;)

Ha nem lesz több módosítás ezen a PR-on, akkor vegyük ki draft-ból és mehet a megrendelőnek. :)

2023-07-28 08:31 UTC, kiskoza requested changes
A kód változások nagy részt jól néznek ki, viszont jó lenne a commitokat egy kicsit rendbe szedni:

* A commit message-ek lehetnének egységesebbek, pl.: `Fix rubocop: X/Y`. A javított szabályt nem érdemes elmagyarázni külön, erre van a rubocop doksi
* Kérlek minden commit tartalmazza a hozzá tartozó rubocop_todo.yml változást - e nélkül nehéz ellenőrizni, hogy tényleg ki lett-e teljesen javítva az adott szabály
* Kerüljük a "Revert" commitokat, ha valamire nincs szükség, akkor fölöslegesen komplikáljuk a commit history-t vele
* Ügyelj rá, hogy ugyanazt a command-ot használd a todo generálására, az eddig használt kapcsolók megtalálhatóak az eredeti todo fájl tetején

A meglévő PR javításához a `git rebase -i origin/master` hasznos lehet, ha még nem használtad, segítek az elején

2023-09-01 12:35 UTC, ebence commented
@kiskoza, ezt Viktor megpróbálja ma még fixálni (de csak munkaidő után).

2023-09-06 08:10 UTC, closed without merging