74 add links
AppMaintainers/beloved-projects pull request #80
Opened 2023-08-25 11:17 UTC by zsuzsibelteky

#74

2023-08-25 15:31 UTC, Gregurevic requested changes

2023-08-25 15:31 UTC, Gregurevic commented on app/views/links/_form.html.erb
> +                <%= f.label :decription, class: 'form-label required' %>
Mintha az issue alatti mintaképek alapján nem lenne required a description.

2023-08-25 15:31 UTC, Gregurevic commented on db/migrate/20230822114552_add_links.rb
> +      t.string :title
Én csak az issue-ban lévő form alapján gondolom így, de ha a `title` és az `url` nem lehet üres, akkor ezt garantáljuk az adatbázis szintjén is légyszi!

2023-08-28 09:06 UTC, kiskoza commented on app/controllers/links_controller.rb
> +  before_action :load_project
a new-nál is jól jöhet, ha authorizáljuk a projektet, mivel a routing egyértelműen meglévő projektre épül ezen a ponton

2023-08-28 09:10 UTC, kiskoza commented on app/policies/link_policy.rb
> +    true
alapvetően itt megfelel az egyszerű `true`, mindenki tud linkeket létrehozni - new esetén, hasonlóan az index-hez, nem egy konkrét objektumról nyilatkozunk, hanem arról, hogy általánosságban láthatja-e a létrehozás formot

2023-08-30 13:38 UTC, zsuzsibelteky commented on db/schema.rb
> +    t.jsonb "services", default: []
az enyém nem volt frissítv, minden jó :D

2023-09-01 09:47 UTC, Gregurevic requested changes
Figyelmetlenségeket látok még a kódban. Légyszi nézd át az előző review-t is, mert nem resolve-oltam onnan minden kommentet!

2023-09-01 09:47 UTC, Gregurevic commented on app/controllers/links_controller.rb
> +    @project = authorize Project.find_by(:project_id), :show?
Itt a `find_by` biztos megtalálja így a rekordot?
Általában így szoktuk használni ezt a függvényt:
```ruby
Resource.find_by(id: params[:resource_id])
```

2023-09-01 09:47 UTC, Gregurevic commented on app/models/link.rb
> +  validates :services, presence: true
Szerintem ilyen mezői nincsenek a `Link` -nek.

2023-09-04 14:22 UTC, Gregurevic approved these changes
Nice work! :)

2023-09-05 07:07 UTC, kiskoza commented
Találtam egy apróságot tesztelés közben, kérlek nézz rá erre a lépéssorozatra:
1. Válassz ki egy projektet
2. Kattints az "Add new link" gombra
3. Ne töltsd ki egyik mezőt se
4. Kattints a "Save" gombra -> az elvárt velidációs hibaüzenet helyett egy rails-es hiba oldal töltődik be

2023-09-05 08:12 UTC, merged