89 account domain validation
AppMaintainers/beloved-projects pull request #92
Opened 2023-10-02 08:47 UTC by zsuzsibelteky

closes #89 

Az account doamin formátuma a linekéhez hasonlóan validálásra került. Az accountok listázásábna pedig már kappintható linkként szerepel.

2023-10-03 05:25 UTC, Gregurevic approved these changes
:+1:

2023-10-03 08:50 UTC, kiskoza requested changes

2023-10-03 08:50 UTC, kiskoza commented on app/models/account.rb
> +  validates :domain, format: { with: %r{\A(http:|https:)//[^.]+\..*\z} }
eddig nem volt kötelező domaint megadni, jó lenne, ha ezután is üresen lehetne hagyni ezt a mezőt

2023-10-26 06:40 UTC, Gregurevic approved these changes
Szerintem így az elvárt módon működik.

2023-10-26 07:16 UTC, kiskoza requested changes

2023-10-26 07:16 UTC, kiskoza commented on app/views/accounts/index.html.erb
> +                      <%= link_to account.domain, target: :_blank, rel: 'noopener' do %>
Akkor is generálunk egy linket, ha nincs megadva domain. Szemmel jelenleg nem látszik, viszont ezt egy későbbi új stílus bevezetésével bármikor kibukhat, mint jövőbeli probléma.

![image](https://github.com/AppMaintainers/beloved-projects/assets/1900366/8eab0ee3-6a9d-4660-8280-1fdf6fd73084)

Kérlek csak akkor rakjunk ki egy linket, ha tényleg van tartalma

2023-11-03 09:28 UTC, Gregurevic requested changes
Apróság.

2023-11-03 09:28 UTC, Gregurevic commented on app/views/accounts/index.html.erb
> +                      <% if !account.domain.blank? %>
Ez tudjuk ennél szebben is írni. Not blank = present.

E helyett:
```ruby
!ittvan.blank?
```

Így:
```ruby
ittvan.present?
```

2023-11-03 10:11 UTC, Gregurevic approved these changes
👍

2023-11-06 10:54 UTC, kiskoza approved these changes

2023-11-06 10:54 UTC, merged