4 add admin user
AppMaintainers/beloved-projects pull request #94
Opened 2023-10-24 13:28 UTC by zsuzsibelteky

closes #4 

Már lehet admin jogosultságokat megadni. Egy admin lát és szerkeszthet minden projectet. Az adminok adhatnak egymásnak admin jogot, e el nem vehetik egymástól, a saját jogukról tudnak lemondani. Aki nem admin az nem látja az admin kezelő felületet és szerkeszteni se tudja a saját jogait.

2023-10-25 06:21 UTC, Gregurevic requested changes
- Hiányzik egy modell validáció.
- Hiányzik egy policy használat.
- Az új nézet kódját légyszi formázd meg.

Ha nem kezdtünk még el teszteket írni a projekten, akkor hagyd figyelmen kívül az alábbiakat. (Bocsi, ezzel sose vagyok tisztában.)
- Minden új endponthoz legalább egy teszt jó lenne, ami a helyes működést ellenőrzi.
- Minden érintett policy-hoz jó lenne legalább két teszt, hogy sima, owner illetve admin user mellett mit kell visszaadnia.
- Hasznos lenne egy új `admin` factory a  ̇`users`-ben, ami alapból admin-ként hozza létre a felhasználót.
- A fent említett modell validáció után feltehetőleg ki kell majd egészíteni a `user` factory-t az új attribútummal.

2023-10-25 06:21 UTC, Gregurevic commented on app/controllers/users_controller.rb
> +  def index
"Aki nem admin az nem látja az admin kezelő felületet" Azt bárki mondhassa!

Ha a `users#index` az admin kezelő felület, akkor a mostani kód alapján el tudom érni egy sima user-rel is. Próbáld ki, hogy csak beírod az url-t.

Szükségünk lenne ennél az endpontnál is egy policy-ra, amit authorize-zal meghívhatunk.

Itt ugye nincs konkrét rekord, amin authorize-t tudunk hívni, ezért átadhatunk szimbólumot is.

```ruby
# így csináltuk a többi kontroller akcióban, ahol volt konkrét rekord, amit authorizáltunk
authorize MyFavouriteModel.find_by(id: params[:id])

# ha nincs konkrét rekordom, de meg szeretném hívni az authorize-t, akkor tudok ilyet csinálni
authorize :my_favourite_model
```

2023-10-25 06:21 UTC, Gregurevic commented on app/views/users/index.html.erb
> +            <thead><tr>
Légyszi a HTML tag-ek kezdődjenek konzisztensen egy tabbal beljebb.
```
<thead>
  <tr>
    <th>
```

2023-10-25 06:21 UTC, Gregurevic commented on app/views/users/index.html.erb
> +            <% @users.each do |user| %>
Légyszi a HTML tag-ek kezdődjenek konzisztensen egy tabbal beljebb.
```
<tbody>
  <% ... %>
    <tr>
      <td>
```

2023-10-25 06:21 UTC, Gregurevic commented on app/views/users/index.html.erb
> +        </th>
Ennek szerint egy `</div>` zárótagnek kellene lennie.

2023-10-25 06:21 UTC, Gregurevic commented on db/migrate/20231013081423_add_admin_user.rb
> +    add_column :users, :admin, :boolean, null: false, default: false
Ehhez légyszi írjunk egy modell validációt is.

2023-10-26 06:36 UTC, Gregurevic requested changes
Egy apróság benne maradt, amúgy szuper.

2023-10-26 07:50 UTC, Gregurevic approved these changes
Cool!

2023-10-26 08:39 UTC, kiskoza requested changes
Normál user-ként még mindig látom az összes projektet, kérlek nézd át még egyszer a teljes issue-t. Az elvárt működéshez szeretném, ha írnánk policy teszteket

2023-11-06 11:01 UTC, kiskoza commented on spec/support/example_groups/policy_example_group.rb
> +    config.include self, type: :serializer, file_path: %r{spec/policies}
ide valószínűleg rosszul küldtem át a mintakódot: `type: :policy` kellene, hogy szerepeljen

2023-11-07 12:54 UTC, merged