page design fixed
AppMaintainers/beloved-projects pull request #95
Opened 2023-10-24 14:48 UTC by zsuzsibelteky

closes #85

2023-10-25 06:26 UTC, Gregurevic requested changes
Légyszi formázd meg jobban a nézetet.

2023-10-25 06:26 UTC, Gregurevic commented on app/views/maintainers/edit.html.erb
> +            <thead><tr>
Légyszi a HTML child tagek kezdődjenek egyel beljebb. Itt: thead, tr, th

2023-10-25 06:26 UTC, Gregurevic commented on app/views/maintainers/edit.html.erb
> +            <tbody>
Légyszi a HTML child tagek kezdődjenek egyel beljebb. Itt: tbody, <%%>, tr, th

2023-10-25 06:26 UTC, Gregurevic commented on app/views/maintainers/edit.html.erb
> +        </th>
Rossz az indentation és rossz a HTML tag is.

2023-10-26 07:21 UTC, kiskoza requested changes
Sokkal szebb lett az oldal, de nem teljesen illesztkedik a meglévő mintába. Kérlek add hozzá a "szokásos" projekt fejlécet. Amennyiben ez már ott van, akkor nem lesz szükség az oldal aján található "Back" gombra

![image](https://github.com/AppMaintainers/beloved-projects/assets/1900366/65104adf-c140-4fc4-b73d-b9544e409ff3)

2023-10-27 11:03 UTC, kiskoza approved these changes

2023-10-27 11:03 UTC, merged